---

- block:
    - validate:
        schema:
          type: object
          properties:
            command:
              type: string
              enum:
                - create_temp_directories
                - delete_remote_files
                - dependency
                - install
                - reset_controller_connection
          required:
            - command
        instance: "{{ ansible }}"

    - include_tasks: '{{ ansible.command }}.yml'
  tags:
    - ansible
