---

- block:
  - validate:
      schema:
        type: object
        additionalProperties:
          - command
        properties:
          fileglob:
            type: string
        required:
          - fileglob
      instance: "{{ ansible }}"
    register: ansible_validated

    - set_fact:
        ansible_v: "{{ ansible_validated.result }}"

  - name: "Delete remote files {{ ansible_v.fileglob }}"
    file:
      path: ~/.ansible/cp
      state: absent
    delegate_to: localhost
    changed_when: false
  tags:
    - ansible_delete_remote_files
