---

- block:
  - validate:
      schema:
        type: object
        additionalProperties:
          - command
        properties:
          directory:
            type: string
          pattern:
            type: string
        required:
          - directory
          - pattern
      instance: "{{ ansible }}"
    register: ansible_validated

    - set_fact:
        ansible_v: "{{ ansible_validated.result }}"

  - name: "Find files {{ ansible_v.pattern }} in directory {{ ansible_v.directory }}"
    find:
      paths: "{{ ansible_v.directory }}"
      patterns: "{{ ansible_v.pattern }}"
    register: ansible_find_return

  - name: "Remove files {{ ansible_v.pattern }} in directory {{ ansible_v.directory }}"
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ ansible_find_return.files }}"
  tags:
    - ansible_delete_remote_files
