---

- block:
    - name: "Install git"
      apt:
        name: git
      become: yes

    - name: "Install Ansible and dependencies"
      import_role:
        name: bedrock.python
      vars:
        python:
          command: pip
          packages:
            - ansible
            - cryptography
            - deepmerge
            - git+git://github.com/Julian/jsonschema.git
            - google-api-python-client

    - name: "Patch broken GCP module code"
      lineinfile:
        path: /usr/local/lib/python3.5/dist-packages/ansible/module_utils/gcp_utils.py
        regexp: self\._credentials\(\)\.with_scopes
        line: "            self._credentials())"
  tags:
    - ansible_install_ansible
