---

- block:
    - name: "Install git and cryptography dependencies"
      apt:
        name:
          - build-essential
          - git
          - libssl-dev
          - libffi-dev
          - python-dev
        state: present
      become: yes

    - name: "Install Ansible and dependencies"
      import_role:
        name: bedrock.python
      vars:
        python:
          command: pip
          packages:
            - ansible
            - cryptography
            - deepmerge
            - git+git://github.com/Julian/jsonschema.git
            - google-api-python-client

    - name: "Patch broken GCP module code"
      lineinfile:
        path: "/home/ubuntu/.local/lib/{{ item }}/site-packages/ansible/module_utils/gcp_utils.py"
        regexp: self\._credentials\(\)\.with_scopes
        line: "            self._credentials())"
      loop:
        - python2.7
        - python3.5

  tags:
    - ansible_install_ansible
